### ISSUE TITLE
请问如何构建离线包

### ISSUE THREAD

**Issue by Moon-404** [mouse0w0/forge-mdk-offline#3]
Recommend 版本有的时候并不满足我的使用需求，所以我想问一下您是如何创建离线包的，我想用魔法自行创建。

**Comment by mouse0w0** [comment]
可以基于本仓库创建一个新的仓库（不要使用`Fork`来复制本仓库），然后在新的仓库中创建Release：
![image](https://user-images.githubusercontent.com/13087252/218651339-907080c3-87a4-4b8b-827c-5cd882635ba7.png)
Github Action会自动创建任务并运行，等待30分钟后即可在Release的文件列表中获取离线包。

**Comment by Moon-404** [comment]
感谢，希望您可以将这个Issue的内容放到Readme中。

**Comment by Moon-404** [comment]
上传的这步失败了，别的都正常，请问是什么原因？

![image](https://user-images.githubusercontent.com/33384538/218664033-7334c0a9-a2e5-437e-9b67-3766ad435362.png)

**Comment by mouse0w0** [comment]
我暂时也不知道该如何解决。

**Comment by mouse0w0** [comment]
可以尝试将仓库的`Settings->Action->General->Workflow permissions`设置项设置为`Read and write permissions`。

**Comment by mouse0w0** [comment]
修改后确实能通过了。

**Comment by Moon-404** [comment]
完成了，感谢。
