### ISSUE TITLE
在生成离线包前改变设置值

### ISSUE THREAD

**Issue by Moon-404** [mouse0w0/forge-mdk-offline#4]
这个离线包应该是相当于把 Github 当网盘用了，让它离线下载。

那么，可以在生成离线包前修改配置文件以修改 Mapping 和 Mixin 吗？

或者说，可不可以让它在生成前，使用 repository 里面的 settings.gradle 和 gradle.build 替换其中的这两个文件再进行后续步骤呢？

我只是想知道这是否可行，如果可以的话，我会去研究具体实现方式的。

**Comment by mouse0w0** [comment]
Github Action支持Python和Git，你可以用这两个工具在构建之前修改任何你想修改的东西，或者从别的地方获取MDK。

**Comment by Moon-404** [comment]
感谢，我已经完成了修改，离线包运行得很好：https://github.com/Moon-404/forge-mixin-parchment-offline
